### ISSUE TITLE
Please check timetables

### ISSUE THREAD

**Issue by nidico** [robbi5/locomore-gtfs#2]
We had a couple of changes in the timetable some weeks before service start (e.g. departure 1818 in RH, 1819 in BLO) - I'd suggest to check against https://locomore.com/de/fahrplan/ again.

**Comment by robbi5** [comment]
I've used the timetable from the booking tool - https://booking.locomore.com/de-DE/orientation/journey-search?origin=8029034&destination=8003231&outboundDate=2016-12-19&passengers[0][type]=A

You may want to check the configuration there too :)

**Comment by robbi5** [comment]
The only difference I could find was LOC 1819, departure from BLO is at 14:28:00.
Did I miss one?

**Comment by nidico** [comment]
> You may want to check the configuration there too :)

Oops, done.

> The only difference I could find was LOC 1819, departure from BLO is at 14:28:00.
> Did I miss one?

No, it's indeed the only one.
