### ISSUE TITLE
add dates until 9.12.2017

### ISSUE THREAD

**Issue by markum** [robbi5/locomore-gtfs#3]
The shedule will (appart from some changes due to works on the tracks) will remain for sure until 9.12.2017, so the the other dates can be added. It is only that we do not sell further than 20.6, but Deutsche Bahn and other companies do that in a similar way.

**Comment by robbi5** [comment]
Thanks :)
Just released 20170106-01: https://github.com/robbi5/locomore-gtfs/releases/tag/20170106-01
